- .circleci/config.yml
Add circleci config file from stevenmburns/circleci-test
Should break
> Adding (wrong) circleci config

- .circleci/config.yml
- PlacementEditor/.gitignore
- PlacementEditor/Dockerfile
- PlacementEditor/Dockerfile.nodejs_ubuntu
- PlacementEditor/README.md
Cached a nodejs build (using ubuntu) to improve circleci performance. (Was 26 min.)
> Build should go faster

- Design Database/Testcases/Switched Capacitor Filter/switched_capacitor_filter_2018_12_10/Spice Netlist/Switched_capacitor_filter.sp
> Design database

- Design Database/Design Examples Library/Wireline/README.md
- Design Database/Design Examples Library/Wireline/W1/Netlist/W1.sp
- Design Database/Design Examples Library/Wireline/W1/README.md
- Design Database/Design Examples Library/Wireline/W2/Netlist/adder.sp
- Design Database/Design Examples Library/Wireline/W2/README.md
- Design Database/Design Examples Library/Wireline/W3/Netlist/W3.sp
- Design Database/Design Examples Library/Wireline/W3/README.md
Wireline circuits have been added to the design examples library in design database
> wireline circuits

- CellFabric/cell_fabric/canvas.py
- CellFabric/cell_fabric/utilities.py
- CellFabric/tests/test_canvas_pex.py
Still buggy but suggest merging so that we can work on SPICE translation.
> Parasitic NetCell Extraction

- CellFabric/cell_fabric/utilities.py
- CellFabric/tests/test_canvas_pex.py
Should be feature complete. Need to run through circuit simulation.
> ParasiticExtraction BugFixes

- .gitattributes
Helps ensure consistent cross-platform end-of-line normalization
> Add .gitattributes directives for common filetypes

- .circleci/config.yml
- Build/ThirdParty/Klayout/Dockerfile.convert
- Build/ThirdParty/Klayout/README.md
- Build/ThirdParty/Klayout/gds2png.sh
- Build/ThirdParty/Klayout/image_png.rb
Integrating a PNG conversion step using Klayout
> Use Klayout to convert GDS to PNG (using Xvfb for use without X).

- .circleci/config.yml
- Build/Dockerfile.build
- Build/Dockerfile.build.python
- Build/ThirdParty/Klayout/Dockerfile
- CellFabric/Dockerfile
- CellFabric/Makefile
- PlaceRouteHierFlow/Dockerfile
- PlaceRouteHierFlow/Makefile.run
- README.md
- compose/Dockerfile
- compose/Makefile
- compose/README.md
- compose/docker-compose.yml
- sub_circuit_identification/Dockerfile
- sub_circuit_identification/Makefile
- sub_circuit_identification/src/check_const.py
A proposal for a new method for running analog flow in containers using make and docker-compose.
This will only work on real Unix, not WSL, due to lack of bind mounts there (WSL2 will fix).
This flow correctly handles dependencies.
> Proposal for Make flow using docker-compose.

- PlaceRouteHierFlow/Makefile.run
- compose/Makefile
- compose/README.md
- sub_circuit_identification/Makefile
This pull request is for fixing a failure to run five_transistor_ota due to missing constraints.
> fixes for missing constraint files + documentation

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
@meghna09 @stevenmburns 
Can you help to review the change? Then I can merge it to master.
In this update, I have fixed the routing shift in capacitor p&r.
Thanks 
Yaguang
> fix cap router shift bug

- compose/README.md
> Desmonddak patch 2

- .circleci/config.yml
- compose/Makefile
- compose/README.md
- compose/docker-core.yml
- compose/docker-dir-type.yml
- compose/docker-vol-type.yml
- compose/native_build.log
… merge).
This version fixes several potential problems when changing volume output, as it
detects the change and rebuilds the containers.  Volumes can now be renamed (we
were stuck on compose_dataVolume previously).  Dependency checking is much better
and should bring up containers more consistently.  Documentation is better aligned
to this mode.
Native mode needs testing, as well as more testing on WSL.
> Simplified make system with flexible volume/dir output (Ready to Merge).

- CellFabric/Cell_Fabric_FinFET__Mock/primitive.py
- CellFabric/cell_fabric/remove_duplicates.py
You can take over this pull request for the multi via primitive routing @arvuce22. 
The current code will do two tracks per signal when it can (to make sure every connection goes over at least two vias). I will leave it upto you to export minvias to a command line option or to do a net-based solution as you were showcasing today.
> [MockPDK] Multi Via primitive routing

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
- PlaceRouteHierFlow/router/GlobalGrid.cpp
@stevenmburns @854768750 
Please help review the updates.
One is to update tile dimension.
The other is to fix a core dump bug. When antu& b is used, there is a core dump error. Do you know the reason? I can not figure it out.
Yaguang
> Fix tile dimension bug and cap bug

- CellFabric/Cell_Fabric_FinFET__Mock/Align_primitives.py
- CellFabric/Cell_Fabric_FinFET__Mock/fabric_Cap.py
- CellFabric/Cell_Fabric_FinFET__Mock/fabric_Res.py
- CellFabric/Cell_Fabric_FinFET__Mock/primitive.py
- CellFabric/Cell_Fabric_FinFET__Mock/test_all.py
- CellFabric/cell_fabric/default.py
- CellFabric/cell_fabric/drc.py
- CellFabric/cell_fabric/gen_gds_json.py
- CellFabric/cell_fabric/gen_lef.py
- CellFabric/cell_fabric/remove_duplicates.py
- CellFabric/tests/test_canvas_pex.py
Continuing #181 in a different branch. Original pull request summarized below:
> Enhanced test coverage shows certain combination of primitive parameters results in opens / shorts. This pull request will address said issues.
> 
> In addition, the following are also rolled in:
> 
> 1. use logging instead of print() statements in canvas
> 2. Miscellaneous refactoring
> Fix primitive routing continued

- .circleci/config.yml
- Build/Dockerfile.build
- PlaceRouteHierFlow/Dockerfile
- PlaceRouteHierFlow/Dockerfile-coverage
- compose/Makefile
- compose/docker-core.yml
Quick branch to migrate to a cached image for with_protobuf.
> Move libboost to the protobuf image

- PlaceRouteHierFlow/PnRDB/ReadLEF.cpp
> Added assertion to check for zero sized array

- .circleci/config.yml
- PlaceRouteHierFlow/run_small_in_docker.sh
Bug in master: core dump not detected during failing run_small_in_docker.sh for PlaceRouteHier
> fix failing run_small

- PlaceRouteHierFlow/router/A_star.cpp
- PlaceRouteHierFlow/router/DetailRouter.cpp
- PlaceRouteHierFlow/router/DetailRouter.h
- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.h
- PlaceRouteHierFlow/router/GcellGlobalRouter.cpp
- PlaceRouteHierFlow/router/GcellGlobalRouter.h
- PlaceRouteHierFlow/router/GlobalGraph.cpp
- PlaceRouteHierFlow/router/GlobalGrid.cpp
- PlaceRouteHierFlow/router/GlobalGrid.h
- PlaceRouteHierFlow/router/Graph.cpp
- PlaceRouteHierFlow/router/Grid.cpp
- PlaceRouteHierFlow/router/Grid.h
- PlaceRouteHierFlow/router/PowerRouter.cpp
- PlaceRouteHierFlow/router/PowerRouter.h
I am going to refactor the global router code.
> rm redundant code

- PlaceRouteHierFlow/Makefile
- PlaceRouteHierFlow/PnRDB/Makefile
- PlaceRouteHierFlow/PnRDB/PnRDBJSON.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/cap_placer/Makefile
- PlaceRouteHierFlow/cap_placer/capplacer.cpp
- PlaceRouteHierFlow/cap_placer/capplacer.h
- PlaceRouteHierFlow/placer/Makefile
- PlaceRouteHierFlow/router/GcellGlobalRouter.cpp
- PlaceRouteHierFlow/router/Makefile
This is a first step to clean up a header circularity issue that
involves GcellGlobalRouter.cpp and the output code on PnRDBJSON.cpp.
> Begin refactoring for using geometry classes to simplify code. READY FOR MERGE

- sub_circuit_identification/basic_library/basic_template.sp
- sub_circuit_identification/basic_library/user_template.sp
- sub_circuit_identification/src/check_const.py
- sub_circuit_identification/src/match_graph.py
- sub_circuit_identification/src/merge_nodes.py
- sub_circuit_identification/src/read_library.py
- sub_circuit_identification/src/read_netlist.py
- sub_circuit_identification/src/temp
- sub_circuit_identification/src/test_parser.py
- sub_circuit_identification/src/write_verilog_lef.py
Code update to generate a spice file for primitives generator.
> Spice dump

- PDK_Abstraction/FinFET14nm_Mock_PDK/Align_primitives.py
I have added cross-coupled pair and level shifter primitives.
> adding cross coupled pair primitive

- Cktgen/cktgen/cktgen/cktgen.py
- Cktgen/cktgen/cktgen/cktgen_physical_from_json.py
- Cktgen/runit-five_transistor_ota.sh
- Cktgen/runit-telescopic_ota.sh
- DetailedRouter/DR_COLLATERAL_Generator/hack84/Process.json
- DetailedRouter/DR_COLLATERAL_Generator/hack84/car_generators.txt
- Experimental/Pysat/gstools-ex.py
- PnRPython/run_sc_dc_dc_converter.sh
- PnRPython/tests/__json_cascode_current_mirror_ota_gr-hacked
- PnRPython/tests/test_check_adr.py
- PnRPython/tests/test_cktgen_dump.py
- Viewer/INPUT/mydesign_dr_globalrouting.json
Initial cobbled together flow to route the telescopic_ota
> Feature/integrate adr [Ready for merge]

- PDK_Abstraction/FinFET14nm_Mock_PDK/Align_primitives.py
Adding cross coupled pair without source connection.
> Cross coupled pair without a source ceonnection

- README.md
- align/compiler/README.md
- align/compiler/compiler.py
- align/compiler/write_verilog_lef.py
- align/config/basic_template.sp
- align/config/user_template.sp
Verilog writer bug and added Readmes
> Compiler fixes

- .circleci/config.yml
- align/cell_fabric/primitive.py
- align/compiler/write_verilog_lef.py
- align/pnr/main.py
- pdks/FinFET14nm_Mock_PDK/canvas.py
- pdks/FinFET14nm_Mock_PDK/fabric_Cap.py
- pdks/FinFET14nm_Mock_PDK/fabric_Res.py
- pdks/FinFET14nm_Mock_PDK/test_res.py
Also adding adder (which uses resistor) to circleci
> Resistor Primitive Fix

- .circleci/config.yml
pngs are not being preserved at the current point in time.
> [circleci] Fix artifact path

- align/pnr/checkers.py
This fixes the shorts through terminal issue
> Fix terminal propagation

- align/cell_fabric/primitive.py
- pdks/FinFET14nm_Mock_PDK/canvas.py
- pdks/FinFET14nm_Mock_PDK/gen_lef.py
- pdks/FinFET14nm_Mock_PDK/layers.json
Adding Metal layers layers in the Cap as blockage
> Resistor drcs

- Cktgen/cktgen/cktgen/consume_results.py
- Cktgen/cktgen/cktgen/techfile.py
Fix required to get routing to complete.
> Removed stopping points (cherry picked from an old branch)

- align/cell_fabric/gen_lef.py
Added Metal blockages for caps.
> adding blockage for caps

- PlaceRouteHierFlow/PnRDB/ReadLEF.cpp
- align/pnr/checkers.py
@Lastdayends This fixes the issue with wrong width rectangles in the PnRDB.
> Change truncation to rounding in the LEF reader

- examples/vco_dtype_12_hierarchical_res/vco_dtype_12_hierarchical_res.setup
- examples/vco_dtype_12_hierarchical_res/vco_dtype_12_hierarchical_res.sp
Adding another example to the examples directory.
This is the same VCO circuit but with resistors.
> Vco with resistors

- align/cmdline.py
- install.sh
- install_tcsh.sh
- setup.sh
- setup_tcsh.sh
I ran the install script and it seems like we need these scripts as well to setup an already installed system.
> Scripts to setup an already installed environment

- PlaceRouteHierFlow/PnRDB/ReadDesignRuleJson.cpp
Fix a bug in json reader file.
Please help review.
> udpate json reader

- Cktgen/check_results.py
- Cktgen/cktgen/cktgen/cktgen.py
- Cktgen/runit.py
- Do not merge global routes
- Revise global route search box
- Fix absolute path in runit
> cktgen global routing updates

- PlaceRouteHierFlow/PnRDB/ReadDesignRuleJson.cpp
- PlaceRouteHierFlow/PnRDB/WriteJSON.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
@arvuce22 
Another boundary is adding for top node. Please check the update.
Yaguang
> udpate writing boundary

- PlaceRouteHierFlow/PnRDB/ReadDesignRuleJson.cpp
- PlaceRouteHierFlow/main.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/router/Graph.cpp
- PlaceRouteHierFlow/router/PowerRouter.cpp
Hi Soner,
I noticed that in GF12 PDK, there are also segment fault error due to the PDK json file.
So I make the same update for the Json reader code in this branch. You can have a test on the design to see whether the power grid segment fault problem is gone.
Yaguang
> update Json reader

- PlaceRouteHierFlow/PnRDB/unit_tests.cpp
- PlaceRouteHierFlow/router/PowerRouter.cpp
@soneryaldiz This is what I think we need to change but in a general way.
> Fix power grid naming

- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
fix via enclosure metal spacing problem
> fix via enclosure

- PlaceRouteHierFlow/main.cpp
- PlaceRouteHierFlow/router/PowerRouter.cpp
- PlaceRouteHierFlow/router/PowerRouter.h
- PlaceRouteHierFlow/router/Router.cpp
- PlaceRouteHierFlow/router/Router.h
- PlaceRouteHierFlow/unit_tests.cpp
@soneryaldiz Here is a PR to work on this issue.
> Different power grid rates for x and y

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
> offset bug

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.h
- PlaceRouteHierFlow/router/PowerRouter.cpp
- PlaceRouteHierFlow/router/PowerRouter.h
- PlaceRouteHierFlow/router/RawRouter.h
add via metal to internal metal, inactivate extra contact for metal extension
> cap pin minlength and power route spacing

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
- PlaceRouteHierFlow/router/Graph.cpp
- PlaceRouteHierFlow/router/Graph.h
- PlaceRouteHierFlow/router/Rdatatype.h
Changed the way how to make a pair of cap pins.
> pair cap pin name

- align/compiler/compiler.py
- align/compiler/preprocess.py
- align/compiler/read_netlist.py
- align/compiler/write_verilog_lef.py
- tests/compiler/test_circuits/basic_template.sp
- tests/compiler/test_circuits/intel_circuit.sp
- tests/compiler/test_circuits/intel_circuit1.sp
- tests/compiler/test_circuits/intel_circuit2.sp
- tests/compiler/test_circuits/intel_circuit3.sp
- tests/compiler/test_circuits/intel_circuit4.sp
- tests/compiler/test_circuits/ota/ota.const
- tests/compiler/test_circuits/ota/ota.setup
- tests/compiler/test_circuits/ota/ota.sp
- tests/compiler/test_circuits/ota/ota.v
- tests/compiler/test_circuits/ota/ota_blocks.sp
- tests/compiler/test_circuits/test1.sp
- tests/compiler/test_circuits/test2.sp
- tests/compiler/test_compiler.py
- tests/compiler/test_current_parser.py
- tests/compiler/test_sizing.py
- tests/compiler/test_writer.py
> Transistor model

- PlaceRouteHierFlow/placer/ILP_solver.cpp
two pins in a block in one net
> ILP solver placer

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/WriteJSON.cpp
- PlaceRouteHierFlow/toplevel.cpp
- align/cmdline.py
- align/config/logging.ini
- align/main.py
- align/utils/logging.py
> convert array to string

- align/primitive/main.py
- tests/primitive/test_get_generator.py
- tests/primitive_pdks/sample_package/__init__.py
- tests/primitive_pdks/sample_package/main.py
- tests/primitive_pdks/sample_pdk/primitive.py
Enhanced get_generator to support PDK abstractions that can be in the form of an installed package, package or conventional.
> READY: PDK as installed package, package, conventional

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/PnRdatabase.cpp
- PlaceRouteHierFlow/PnRDB/PnRdatabase.h
- PlaceRouteHierFlow/router/Router.cpp
- PlaceRouteHierFlow/router/Router.h
- align/pnr/checkers.py
- align/pnr/main.py
- align/pnr/toplevel.py
- tests/test_cmdline.py
> Move functionality from toplevel.cpp to toplevel.py (more control flow of PnR in python)

- .circleci/config.yml
- .dockerignore
- .gitignore
- CMakeLists.txt
- README.md
- tests/gdsconv/test_gds_json.py
- tests/gdsconv/test_txt_pretty_json.py
Generated filenames were still the same on two tests causing race condition & JSON reading errors. This should fix it.
Will continue working on supporting gdb in develop mode in a separate PR.
> [CI] Fix test parallelism issues

- .circleci/config.yml
- runcoverage.py
- setup.py
- tests/test_cmdline.py
> [setup] Debug Mode + Fix build-test-coverage

- .circleci/config.yml
- bin/test_wheel.sh
- tests/test_cmdline.py
> [circleci] Optimize commit workflow

- align/config/logging.ini
- align/pnr/pnr_compiler.py
Do color logging correctly using the .ini file.
> Using colorlog in the .ini file

- Viewer/index.html
- align/cell_fabric/pdk.py
- align/compiler/match_graph.py
- align/primitive/main.py
- tests/compiler/test_results/high_speed_comparator_align.const.json
- tests/compiler/test_results/high_speed_comparator_multiconnection.const.json
- tests/compiler/test_results/high_speed_comparator_portlocation.const.json
- tests/compiler/test_results/high_speed_comparator_symmnet.const.json
- tests/compiler/test_user_constraint.py
Constraint translation should preserve the order of blocks.
> WIP: Bug in constraint translation

- PlaceRouteHierFlow/PnRDB/PnRdatabase.cpp
> Use correct tuple field for power signal name

- README.md
- align/pnr/main.py
- setup.py
- tests/pnr/test_cktgen_dump.py
> Better errors messages and ability to generate --build-type=Release pip builds.

- align/pnr/toplevel.py
- align/primitive/default/mos.py
The total cell height is integer multiple of row height
> Cells with integer multiple of row height

- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
missing lower cost solutions in enumerate mode
> Enumerate smallblk v0

- align/cmdline.py
- align/main.py
- align/pnr/main.py
- align/pnr/toplevel.py
> WIP: Add bottom_up routing engine

- PlaceRouteHierFlow/thirdparty/boost.cmake
@parijatm @soneryaldiz @854768750 We should merge this with master as soon as we can.
> Fix boost path

- .circleci/config.yml
@kkunal1408 Removing these tests until we have a fix. Clean them from `.circlci/config.yml` after they are fixed.
> Remove failing tests from CI run on a merge

- .circleci/config.yml
> Retry fixing CI on merges

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
Fix leak by calling delete_lp;
Scale the max iter by effort for enumerate calculation
> Memory leak in lp when no solution not found

- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/pdk/finfet/examples/ring_oscillator/ring_oscillator.const.json
- align/pdk/finfet/examples/ring_oscillator/ring_oscillator.setup
- align/pdk/finfet/examples/ring_oscillator/ring_oscillator.sp
- align/pdk/finfet/examples/ring_oscillator/ring_oscillator_stage.const.json
- tests/pdk/finfet/test_examples.py
align/pdk/finfet/examples/ring_oscillator fails when power and ground not specified. To reproduce:
```bash
schematic2layout.py $ALIGN_HOME/align/pdk/finfet/examples/ring_oscillator -p $ALIGN_HOME/align/pdk/finfet -c
...
File "/home/soneryal/projects/vanilla/april15/ALIGN-public/align/pnr/toplevel.py", line 255, in place_and_route
place( DB=DB, opath=opath, fpath=fpath, numLayout=numLayout, effort=effort, idx=idx)
File "/home/soneryal/projects/vanilla/april15/ALIGN-public/align/pnr/toplevel.py", line 206, in place
curr_plc = PnR.PlacerIfc( current_node, numLayout, opath, effort, DB.getDrc_info(), hyper)
IndexError: vector::_M_range_check: __n (which is 5) >= this->size() (which is 5)
```
@854768750 , could you please take a look?
> WIP: revised ring_oscillator

- align/pnr/adr/README.md
> Start ADR integration

- align/main.py
- align/pnr/main.py
@854768750 This should do what want for #705 
```
schematic2layout.py $ALIGN_HOME/examples/cascode_current_mirror_ota --flow_stop 3_pnr:prep
```
> Split flow stage 3_pnr into several parts

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
Populate the oData with all valid solutions instead of just the selected ones
> store least cost soultions and fix normalization

- PlaceRouteHierFlow/placer/SeqPair.cpp
- align/cell_fabric/postprocess.py
- align/cell_fabric/remove_duplicates.py
- align/gui/mockup.py
- align/main.py
- align/pnr/DB_wrapper.py
- align/pnr/checker.py
- align/pnr/main.py
- align/pnr/render_placement.py
- align/pnr/toplevel.py
- align/primitive/default/canvas.py
- align/primitive/default/via.py
- examples/VCO_type2_65/VCO_type2_65.setup
- examples/VCO_type2_65/VCO_type2_65.sp
- examples/vco_dtype_12_hierarchical_res_constrained/VCO_type2_65.const.json
- tests/pnr/test_render_placements.py
To duplicate the slowness issue, try: `vco_dtype_12_hierarchical_res_constrainted, n=200`
> Fix hierarchical placement verilog

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
Opening PR so I can view the changes in the Github GUI
> Flip x y enum placer

- PlaceRouteHierFlow/placer/SeqPair.cpp
enumerate mode did not check for flips which checking for num iterations.
> count flips in enumerate check

- align/pdk/finfet/examples/comparator/comparator.const.json
- align/pdk/finfet/examples/comparator/comparator.setup
- align/pdk/finfet/examples/comparator/comparator.sp
- align/pdk/finfet/layers.json
- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet/helper.py
- tests/pdk/finfet/test_comparator.py
- Updated comparator netlist
- Created helper routines for future comparator tests with constraints
This PR is ready for review.
> Test harness for comparator with constraints

- align/compiler/match_graph.py
- tests/pdk/finfet/test_comparator.py
@kkunal1408 , subcircuit identification was creating illegal constraints. Please review and let's check whether there are any other places where flow tries to append illegal constraints.
> Bug fix in compiler

- align/main.py
- align/pdk/finfet/resistor.py
- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet/test_metadata.py
This feature allows primitive generator to pass additional metadata to __primitives__.json.
> propagate instance to __primitives__

- align/main.py
- align/pdk/finfet/resistor.py
- align/primitive/main.py
Access netlist_dir from inside generate_primitive.
> add netlist_dir key to generate_primitive

- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/pnr/write_constraint.py
- tests/constraints/.gitignore
- tests/constraints/circuits.py
- tests/constraints/test_constraint.py
- tests/constraints/utils.py
- tests/files/test_results/high_speed_comparator_align.pnr.const.json
- tests/files/test_results/high_speed_comparator_multiconnection.pnr.const.json
- tests/files/test_results/high_speed_comparator_orderblock.pnr.const.json
- tests/files/test_results/high_speed_comparator_portlocation.pnr.const.json
- tests/files/test_results/high_speed_comparator_symmnet.pnr.const.json
Test case: `tests/constraints/test_constraint.py::test_order_abut()`
> Order with Abut

- align/cell_fabric/canvas.py
- tests/cell_fabric/__json_join_wires_four_gold
- tests/cell_fabric/test_canvas_join_wires.py
Changing the join_wires function to account for the netType of the wire.
> fix join_wires after adding nettype blockage

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- README.md
> Fixed bad use of array on stack

- align/compiler/match_graph.py
- align/compiler/read_setup.py
- align/config/user_template.sp
- align/pdk/finfet/transistor_array.py
- align/pnr/checkers.py
- align/pnr/main.py
- examples/buffer/buffer.setup
- examples/inverter_v1/inverter_v1.setup
- examples/inverter_v2/inverter_v2.setup
- examples/inverter_v3/inverter_v3.setup
- tests/pdk/finfet/circuits.py
- tests/pdk/finfet/test_circuits.py
Please see the failing test(s): `test_comparator_pg`
@kkunal1408 , there are spurious nets showing up in the final layout.
@Lastdayends , router left an open.
@meghna09 fyi.
> Bogus nets in generated layout

- .gitignore
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/cmdline.py
- align/main.py
- align/pnr/main.py
- align/pnr/toplevel.py
- dev/Experimental/SimulatedAnnealing/simulated_annealing.py
- setup.py
- tests/pdk/finfet/.gitignore
- tests/pdk/finfet/test_circuits.py
- tests/pdk/finfet/test_placer.py
- tests/pdk/finfet/utils.py
Placement algorithm is highly sensitive to random number generator seed:
`pytest tests/pdk/finfet/test_placer.py -k seed -v -s`
Running this test will print below and also save cost trajectory plot:
```
seed=0 hpwl=793380 area=3429216000
seed=7 hpwl=858180 area=4164048000
seed=1981 hpwl=840180 area=3919104000
seed=2021 hpwl=873480 area=4164048000
```
> Placer Sensitivity To RNG Seed

- .circleci/config.yml
Adding a python3.10 wheel build to CI
> New Python in CI

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/PnRDB/ReadDesignRuleJson.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/compiler/create_array_hierarchy.py
- align/compiler/match_graph.py
- align/pnr/build_pnr_model.py
- align/schema/constraint.py
- examples/variable_gain_amplifier/variable_gain_amplifier.const.json
- examples/vga_stage/vga_stage.const.json
- examples/vga_stage/vga_stage.sp
- tests/compiler/test_user_constraint.py
- tests/files/test_circuits/high_speed_comparator_align/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_broken/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_compactplacement/high_speed_comparator.const.json
- tests/files/test_circuits/high_speed_comparator_compactplacement/high_speed_comparator.sp
- tests/files/test_circuits/high_speed_comparator_multiconnection/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_orderblock/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_portlocation/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_symmblock/high_speed_comparator.setup
- tests/files/test_circuits/high_speed_comparator_symmnet/high_speed_comparator.setup
- tests/files/test_results/high_speed_comparator_compactplacement.const.json
- tests/files/test_results/high_speed_comparator_compactplacement.pnr.const.json
* Refactored the ILP routine
* Two different calls to frame and solve ILP: one for LL and UR flush respectively
* Calculate slack using the \delta x and \delta y
* Honor symmetry group and align constraints while moving using slack
> center align blocks in place of left flush

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- examples/vga_stage/vga_stage.const.json
* Updated the HPWL calculation in ILP using auxiliary boundary coordinate variables for all nets.
Improvement in HPWL shown in the below plot; Green points indicate the new HPWL calculated from ILP.
> calculate accurate HPWL in ILP

- align/pnr/toplevel.py
Compare python evaluated and C++ evaluated HPWLs for the right hierarchy pairs.
> Iterate over hierarchies to find matching hierarchy

- PlaceRouteHierFlow/placer/ILP_solver.cpp
* `integration` regression is broken in `master` due to the recent fix to calculate HPWL accurately in ILP.
* Reverting the HPWL calculation to the erroneous one.
* Improve the runtime before checking in this fix.
> revert HPWL calculation to old version

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/Placer.h
- PlaceRouteHierFlow/placer/PlacerHyperparameters.h
- PlaceRouteHierFlow/placer/PlacerIfc.cpp
- PlaceRouteHierFlow/placer/PlacerIfc.h
- PlaceRouteHierFlow/thirdparty/symphony.cmake
- align/cmdline.py
- align/pnr/toplevel.py
Two ways to handle SIGINT in Symphony
* Disable it totally during build
* Enable/Disable using save/restore signal handler
> SIGINT handling with Symphony solver

- tests/pdk/finfet_pdk/test_placement_grid.py
Move the test script to the new directory.
> Fix Incorrect Merge 

- .circleci/config.yml
- README.md
> Add comments on how to run CI locally.

- align/pnr/checker.py
- align/pnr/toplevel.py
- align/schema/constraint.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pnr/test_check_place_on_grid.py
- tests/schema/test_placement.py
This PR verifies if all instances of a primitive satisfies the associated PlaceOnGrid constraints.
> Validate PlaceOnGrid constraints

- tests/constraints/test_constraint.py
> AspectRatio Add a failing test

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/ReadDesignRuleJson.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/Placer.h
- PlaceRouteHierFlow/placer/PlacerHyperparameters.h
- align/pdk/finfet/transistor_array.py
- align/pnr/checker.py
- align/pnr/grid_constraints.py
- align/pnr/main.py
- align/pnr/toplevel.py
- align/schema/types.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pnr/test_grid_constraints.py
When a primitive with PlaceOnGrid constraint is instantiated, all upper hierarchy instantiating the primitive shall satisfy the associated constraints. 
Failing test for feature development: `test_placement_grid.py::test_hierarchy`
> Propagate PlaceOnGrid constraint thru hierarchy

- align/schema/constraint.py
- align/schema/hacks.py
- align/schema/subcircuit.py
- align/schema/types.py
> Fix reporting error when checker finds infeasible solution.

- align/primitive/main.py
- pdks/Bulk65nm_Mock_PDK/layers.json
- pdks/FinFET14nm_Mock_PDK/layers.json
I have added max cap unit size limit in layers.json files
> adding max limit for unit cap

- align/compiler/read_library.py
- align/pdk/finfet/basic_template.sp
- align/pdk/finfet/user_template.sp
- tests/pdk/finfet_pdk/test_miscellaneous.py
Check if a PDK provides templates and prioritize over the defaults under align/config: 
`basic_template.sp`
`user_template.sp`
> Check if a PDK provides templates

- align/pdk/finfet/layers.json
Added mock interconnect resistance and capacitance numbers.
> Add Interconnect R&C to align/pdk/finfet

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- align/pdk/finfet/transistor_array.py
- align/pnr/toplevel.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pdk/finfet_pdk/test_transistor_array.py
- A new test case: comparator with manual constraints and PlaceOnGrid constraints for MOS primitives. 
`pytest test_placement_grid.py::test_cmp_fp2_w_grid -vv --log-cli-level INFO`
~ 25 secs w/o PlaceOnGrid
~ 35 secs w/ PlaceOnGrid
- Concurrency bug fix (use monkeypatch instead of os.environ)
- Bug fix in placement engine: multiple ored_terms
> New test with PlaceOnGrid

- align/pnr/toplevel.py
Minor fix for design with CC caps
> Only run the cap placer during the first placement run

- align/pnr/write_constraint.py
- align/schema/constraint.py
- tests/constraints/test_constraint.py
- Added a new constraint called NetPriority
- Code revisions for flake8
- Minor refactoring
> New Constraint: NetPriority

- PlaceRouteHierFlow/placer/SeqPair.cpp
- tests/pdk/finfet_pdk/test_placer.py
To reproduce please run: `/tests/pdk/finfet_pdk/test_placer.py::test_hang_3`
Placer hangs just after:  `DEBUG    PnR.placer.design.MergeNewBlockstoSymmetryGroup:placer.py:56 New symmetric group`
> Placer hangs during constraint processing

- align/cell_fabric/canvas.py
- align/cell_fabric/drc.py
- tests/cell_fabric/test_canvas_drc_max_via.py
This PR introduces a new, optional design rule for via: Maximum number of adjacent via
> Max Number of Vias on Adjacent Tracks

- .circleci/config.yml
- align/compiler/compiler.py
- align/compiler/create_database.py
- align/compiler/preprocess.py
- align/schema/parser.py
- tests/compiler/test_database.py
- tests/compiler/test_library_parsing.py
Improve test coverage of compiler code.
1st version, target of 100% coverage:
> Coverage-compiler

- align/main.py
- align/primitive/__init__.py
- align/primitive/main.py
@kkunal1408 , this PR is ready for review.
> Reduce primitive generation in align/main.py to a single call

- align/pdk/finfet/canvas.py
- align/pdk/finfet/layers.json
- align/pdk/finfet/transistor_array.py
- align/pnr/build_pnr_model.py
- align/pnr/write_constraint.py
- align/schema/constraint.py
- align/schema/translator.py
- tests/files/test_results/high_speed_comparator_align.pnr.const.json
- tests/files/test_results/high_speed_comparator_compactplacement.pnr.const.json
- tests/files/test_results/high_speed_comparator_multiconnection.pnr.const.json
- tests/files/test_results/high_speed_comparator_orderblock.pnr.const.json
- tests/files/test_results/high_speed_comparator_portlocation.pnr.const.json
- tests/files/test_results/high_speed_comparator_symmblock.pnr.const.json
- tests/files/test_results/high_speed_comparator_symmnet.pnr.const.json
- tests/pdk/finfet_pdk/test_circuits.py
This PR introduces a new constraint that allows user to specify a list of regions.
> New constraint: Floorplan

- tests/compiler/test_user_constraint.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_circuits_partial_routing.py
- tests/pdk/finfet_pdk/test_placement_grid.py
> Update the failing test on master

- align/schema/checker.py
- align/schema/constraint.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/schema/test_constraint.py
This PR:
- changes Floorplan to a UserConstraint that is to a HardConstraint
- add validation to Floorplan constraint to improve readability of errors
> Improve user experience for invalid floorplan

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- tests/pdk/finfet_pdk/test_placer.py
`tests/pdk/finfet_pdk/test_placer.py::test_sub_1` fails due to suboptimal placement shown below. The annotated red arrows show the redundant gap which results in longer wire length for nets A1 and A2.
> Suboptimal placement

- align/compiler/preprocess.py
- align/compiler/util.py
- align/pnr/manipulate_hierarchy.py
- tests/integration/test_integration.py
- tests/pdk/finfet_pdk/test_miscellaneous.py
Please see the test: `tests/pdk/finfet_pdk/test_miscellaneous.py::test_floating_pin`:
```
.subckt ckt_floating_pin d g s1 s2 vccx vssx floating_pin
qp0 d g s1 vccx p m=1 nf=2 w=90e-9
qn0 d g s2 vssx n m=1 nf=2 w=90e-9
.ends ckt_floating_pin
.END
```
> Tolerate Floating Pins

- PlaceRouteHierFlow/thirdparty/boost.cmake
Fix broken boost compile in master
> revert boost link

- align/compiler/preprocess.py
- align/schema/types.py
- examples/powertrain_thermo/powertrain_thermo.sp
- tests/pdk/finfet_pdk/test_annotation.py
This PR fixes the failure on master.
> Remove the hack for single element subcircuits in remove_dummy_devices

- tests/pdks/test_mos.py
undo the changes in test_mos.py
> fix master

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pdk/finfet_pdk/utils.py
To reproduce: `pytest -vv -s tests/pdk/finfet_pdk/test_placement_grid.py::test_cs_on_grid_v`
> PlaceOnGrid fails for vertical and half poly pitch offset

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- tests/pdk/finfet_pdk/test_digital.py
To reproduce: `pytest -vv -s tests/pdk/finfet_pdk/test_digital.py::test_dig_1`
> PlaceOnGrid fails for a single instance

- align/primitive/main.py
- examples/linear_equalizer/linear_equalizer.sp
- examples/single_to_differential_converter/single_to_differential_converter.sp
- pdks/Bulk65nm_Mock_PDK/cap.py
- pdks/Bulk65nm_Mock_PDK/fabric_Cap.py
- pdks/Bulk65nm_Mock_PDK/gen_param.py
- pdks/Bulk65nm_Mock_PDK/layers.json
- pdks/Bulk65nm_Mock_PDK/models.sp
- pdks/Bulk65nm_Mock_PDK/mos.py
- pdks/FinFET14nm_Mock_PDK/cap.py
- pdks/FinFET14nm_Mock_PDK/fabric_Cap.py
- pdks/FinFET14nm_Mock_PDK/gen_param.py
- pdks/FinFET14nm_Mock_PDK/models.sp
- pdks/FinFET14nm_Mock_PDK/mos.py
- tests/compiler/test_parser.py
- tests/files/test_circuits/test2.sp
- tests/pdks/test_cap.py
- tests/pnr/test_cc.py
Adding 'length' and 'width' parameters for caps
> adding length and width for cap

- align/primitive/main.py
- align/schema/constraint.py
- pdks/Bulk65nm_Mock_PDK/Align_primitives.py
- pdks/Bulk65nm_Mock_PDK/mos.py
- pdks/FinFET14nm_Mock_PDK/Align_primitives.py
- pdks/FinFET14nm_Mock_PDK/gen_param.py
- tests/pdks/test_constrained_generator.py
> add tests for primitive parameters

- align/cell_fabric/gen_lef.py
- align/primitive/main.py
- pdks/Bulk65nm_Mock_PDK/gen_param.py
- pdks/Bulk65nm_Mock_PDK/layers.json
- pdks/Bulk65nm_Mock_PDK/mos.py
in this PR we are adding continuous width feature for bulk technologies
> Initial changes for continuous width in bulk

- .circleci/config.yml
- align/pdk/finfet/gen_param.py
- align/schema/constraint.py
- tests/constraints/test_constraint.py
Without this validation, the flow gets stuck in an infinite loop.
> Validate existence of power and ground ports

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/design.cpp
- align/pdk/finfet/digital.py
- align/pnr/render_placement.py
- tests/pdk/finfet_pdk/test_digital.py
Please see the two test cases:
`tests\pdk\finfet_pdk\test_digital.py:test_dig_4`
`tests\pdk\finfet_pdk\test_digital.py:test_dig_5`
Both tests are failing with or without `--place_using_ILP`
> Placement Engines cannot find a solution

- align/pdk/finfet/gen_param.py
- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet_pdk/circuits.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_circuits_partial_routing.py
- tests/pdk/finfet_pdk/test_placement_grid.py
This PR adds a new, hierarchical circuit example with place on grid constraints. The test is intentionally disabled and will be enabled in a future PR for triage and debug.
> New circuit for align/pdk/finfet

- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/router/GcellGlobalRouter.cpp
- align/pnr/build_pnr_model.py
Modification in the structure for Routing_Layers to match the Per Net Layer constraints in this thread
> Update: data structure for Routing_Layers and related files

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
- align/pnr/placer.py
- tests/pdk/finfet_pdk/test_circuits.py
Reproduce using:
`pytest -s -v -- tests/pdk/finfet_pdk/test_annotation.py::test_dcl`
The test exits at the first instance of mismatch between HPWL_ILP and HPWL_extend
> Fix HPWL mismatch

- dev/Experimental/PlacePy/enumerate_floorplans.py
> Prototype sequence pair and variant enumeration in Python

- tests/pnr/test_grid_constraints.py
You can run it using:
```
pytest -s -vv tests/pnr/test_grid_constraints.py::test_gen_constraints_standard_cells
```
> Add a new test corresponding to failing standard cell case

- align/gui/mockup.py
@soneryaldiz You should be able to merge this into your demo PR.
> Quick fix for domain name

- align/compiler/find_constraint.py
- align/compiler/match_graph.py
- align/main.py
- align/pdk/finfet/examples/comparator/comparator.const.1.json
- align/pdk/finfet/examples/comparator/comparator.const.2.json
- align/pnr/checker.py
- align/pnr/main.py
- align/pnr/write_constraint.py
- align/schema/constraint.py
- dev/Experimental/PlacePy/formulate_ilp.py
- examples/common_source/common_source.const.json
- tests/constraints/test_constraint.py
- tests/pdk/finfet_pdk/_CKT_PLACE_CMP_1_0.placement_verilog.json
- tests/pdk/finfet_pdk/test_benchmark_place.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_circuits_partial_routing.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pdk/finfet_pdk/test_placer.py
- tests/placer_pythonic/test_placer_pythonic_sp.py
- tests/schema/test_constraint.py
> Constraint Revisions and Clean up

- PlaceRouteHierFlow/router/A_star.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.h
- PlaceRouteHierFlow/router/GcellGlobalRouter.cpp
- PlaceRouteHierFlow/router/GlobalGraph.cpp
- PlaceRouteHierFlow/router/GlobalGrid.h
- PlaceRouteHierFlow/router/Graph.cpp
- PlaceRouteHierFlow/router/Graph.h
- PlaceRouteHierFlow/router/Grid.cpp
- PlaceRouteHierFlow/router/Grid.h
- PlaceRouteHierFlow/router/PowerRouter.cpp
- PlaceRouteHierFlow/router/RawRouter.cpp
- PlaceRouteHierFlow/router/Rdatatype.h
speedup router using vtune.
Method: change the code implementation, do not change the algorithm and logic
switched_capacotpor_filter
Result: total time 800s -> 216s (3.7x), routing time: 751s -> 169s (4.4x)
> Speedup router

- PlaceRouteHierFlow/router/A_star.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
- PlaceRouteHierFlow/router/Grid.h
- PlaceRouteHierFlow/router/Rdatatype.h
- tests/pnr/test_router_multi_pin.py
- tests/pnr/utils.py
To reproduce: `pytest -v tests/pnr/test_router_multi_pin.py`
> Failing Unit Router Tests

- align/compiler/preprocess.py
- align/main.py
- align/pnr/main.py
- print server name for viewer
- keep files under work directory
- reduce info messages
> Minor Revisions

- .circleci/config.yml
- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/ILP_Place.cpp
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/cell_fabric/pdk.py
- align/cmdline.py
- align/gdsconv/gds2json.py
- align/gdsconv/gds2lefjson.py
- align/gdsconv/gds2primitive.py
- align/main.py
- align/pnr/main.py
- align/pnr/placer.py
- align/pnr/router.py
- align/primitive/main.py
- bin/build_wheel.sh
- bin/gen_gds_from_json.py
- bin/gen_primitive_from_gds.py
- tests/gdsconv/black_box_test/hsc_black_box_test/high_speed_comparator_auto.sp
- tests/gdsconv/black_box_test/test_black_box.py
* Create a new generator type `black_box` using the syntax `* @: Generator(name='black_box')` in the SPICE file
* Convert the GDS file of black box primitive to LEF, GDS.JSON, JSON and PLACEMENT_LEF files
* Obtain pin information from labels in the GDS
> Black box generator from gds

- README.md
- align/cell_fabric/gen_gds_json.py
- align/pnr/main.py
Use the `blockPins` data in the `hierNode` to add pin labels to the` .python.gds` file.
Add help for install issues with `libOsiCbc.so file not found error` in `README.md`.
> Add labels to the python.gds file

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/design.cpp
- align/compiler/find_constraint.py
Comment the symm block constraint generation in the symm net constraint routine.
> Remove symm block constraint added by the symmnet constraint

- align/cmdline.py
- align/gui/mockup.py
- align/main.py
- align/pnr/main.py
- align/pnr/placer.py
This argument will help invoke GUI from the docker containers.
> Add a port arg to `schematic2layout.py`
