- sub_circuit_identification/src/match_graph.py
- sub_circuit_identification/src/read_netlist.py
- sub_circuit_identification/src/util.py
Errors in CI due to networkx deprecating g.node[] in favor of g.nodes[]
> Replace usages of g.node[] with g.nodes[]

- PDK_Abstraction/FinFET14nm_Mock_PDK/fabric_Cap.py
- PlaceRouteHierFlow/cap_placer/capplacer.cpp
- PlaceRouteHierFlow/testcase_example/switched_capacitor_filter.lef
@stevenmburns 
Although visually there is no via bug in the switched capacitor combination, I did find the bug exists. 
The reason is due to the error in the lef file.
After the M1 port in cap_12 is removed, the via bug should be fixed. (There is an assumption, only M2 pins are provided for unit cap.)
By the way, the location of the via generated by the layout visualization tool is not correct.
Yaguang
> correct unit cap (cap 12) pin content

- Circuit/circuit/core.py
- Circuit/tests/ota.sp
- Circuit/tests/test_combined.py
- Circuit/tests/test_core.py
Quick & dirty implementation of find_repeated_subckts. 
Algorithm attempts to maximize the number of elements while minimizing the number of nets in discovered subckts.
Calling replace_repeated_subckts will also modify the existing graph in addition to returning the discovered subckts.
> Demo subgraph isomorphism based find_repeated_subckts

- PlaceRouteHierFlow/PnRDB/PnRdatabase.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.cpp
- PlaceRouteHierFlow/router/GcellDetailRouter.h
- PlaceRouteHierFlow/router/GcellGlobalRouter.cpp
- PlaceRouteHierFlow/router/GlobalGraph.cpp
@kkunal1408 
I found that in different machine, lp solver might get stuck when the available memory is diffferent. Maybe that's the reason why there is a difference between the cases when you run it and when I run it.
One more command in the code to exit LP in 60s. Now you can try this code with GF design (1h22min for me).
That's a temporary solution.  I am running TI_SAR and get stuck in top level too (3h to go to top level). You can try other designs. Let me know the results about other designs. Thanks.
Yaguang
> upto 60s for lp solver

- align/primitive/default/canvas.py
This should allow our via2 enclosures in 22FFL (which cause a stoppoint ordering check violation) to be ignored during primitive generation.
> Thread the check flag throughout DefaultCanvas

- PlaceRouteHierFlow/router/PowerRouter.cpp
- PlaceRouteHierFlow/router/PowerRouter.h
@kkunal1408 
Example inverter_v1.
Crash if INV_LVT has a constraint "SymmBlock ( {xm0} , {xm1} )".
The test case can be reproduced by removing "and name not in lib_names" from line 188 in align/compiler.py
This constraint make that there is no space to create power grid. Then P&R fails. 
A assert is added when power grid is empty.
> add assert when no space for power grid construction

- PlaceRouteHierFlow/cap_placer/capplacer.cpp
Gds is correct but checker reports short issues because names of capacitor pins are wrong. "PLUS" and "MINUS" are reversed in Nets_neg and Nets_pos.
> capplacer name

- PlaceRouteHierFlow/PnRDB/Lexer.h
@soneryaldiz Should fix the powertrain verilog parsing issues.
> Allow square brackets in net names (verilog)

- examples/powertrain/powertrain.sp
- examples/powertrain_binary/powertrain_binary.sp
- examples/powertrain_thermo/powertrain_thermo.sp
Updated m,nf,nfin in examples/powertrain* to follow the convention as agreed upon during the virtual F2F:
nfin : Number of fins in an atomic transistor (equivalent to W in bulk technologies) 
nf : Number of fingers that share diffusion
m : Number of instances of the transistor specified with nfin and nf
> updated m,nf,nfin

- build/Dockerfile.base
- build/Dockerfile.build.python
- build/Dockerfile.native
- build/Dockerfile.native16
Upgrading to pytest version 6.0.0 breaks nightly regressions by causing INTERNALERROR upon encountering failed DRC checks. This error causes the overall regression to silently pass without running all circuits.
Reverting to pytest version 5.4.3 in Dockerfile.base.
> Nightly INTERNALERROR fix

- tests/test_cmdline.py
CI should  fail according to Kunal with the 'adder' testcase added.
> Add the 'adder' testcase that is supposed to fail in CI

- align/pnr/main.py
- examples/five_transistor_ota_high_frequency/five_transistor_ota_high_frequency.const
- examples/five_transistor_ota_high_frequency/five_transistor_ota_high_frequency.setup
- examples/five_transistor_ota_high_frequency/five_transistor_ota_high_frequency.sp
- examples/telescopic_ota_multi_connection/telescopic_ota_multi_connection.const
- examples/telescopic_ota_multi_connection/telescopic_ota_multi_connection.setup
- examples/telescopic_ota_multi_connection/telescopic_ota_multi_connection.sp
@parijatm @stevenmburns @854768750 @meghna09 
When I use the commend below:
pytest -vv --runnightly -k multi -- tests/integration
Error happens like:
ERROR    align.cmdline:cmdline.py:109 Fatal Error. Cannot proceed
Traceback (most recent call last):
File "/home/liyg/Desktop/Research/ALIGN-public/align/cmdline.py", line 107, in parse_args
return schematic2layout(**vars(arguments))
File "/home/liyg/Desktop/Research/ALIGN-public/align/main.py", line 75, in schematic2layout
variants = generate_pnr(topology_dir, primitive_dir, pdk_dir, pnr_dir, subckt, nvariants, effort, check, extract, gds_json=python_gds_json)
File "/home/liyg/Desktop/Research/ALIGN-public/align/pnr/main.py", line 79, in generate_pnr
assert shared_object_path.is_file(), f"{shared_object_path} not found. Has it been built?" …
> Example testcases

- PlaceRouteHierFlow/Makefile
This is required for everything to compile of Intel's SLES11 systems.
@soneryaldiz @parijatm @854768750 @Lastdayends 
There are a few things I'd like to discuss.
> Fix up Makefile so that Pybind11 stuff links correctly on Intel SLES12 machines

- PlaceRouteHierFlow/placer/ILP_solver.cpp
When ILP solver fails, the info will be logged to a file. And it takes long time and does not finish before another ILP solver begins. Then the output stream fails.
> disable logging ILP info to file

- align/schema/checker.py
- align/schema/constraint.py
- align/schema/constraint_placement.py
- align/schema/types.py
- tests/schema/test_checker.py
- tests/schema/test_constraint.py
- tests/schema/test_constraint_placement.py
- tests/schema/test_parser.py
> [schema] Formalize Ordering & Alignment constraints

- align/pdk/finfet/canvas.py
- align/schema/pdk.py
- pdks/Nonuniform_mock_pdk/canvas.py
- tests/schema/test_pdk.py
- Retire LayerViaSet due to replicated data to be re-introduce in a future PR as needed
- Generate ADR collaterals from the new PDK schema. Single metal template instance.
These collaterals to be tested with ADR in a future PR. 
@stevenmburns , this is ready for review.
> READY: Generate Intel ADR collaterals from the new PDK schema

- align/pnr/main.py
- tests/test_cmdline.py
Instead of copying all files in a given directory to setup PnR, we determine which files we need and just copy those.
> Remove iterdir from PnR setup

- align/compiler/match_graph.py
- align/schema/checker.py
- align/schema/constraint.py
- examples/ring_oscillator/ring_oscillator.const.json
- tests/compiler/test_user_constraint.py
- tests/schema/test_checker.py
- tests/schema/test_constraint.py
CI is failing on master because of some weird constraints being generated for ring_oscillator. Could you please take a look @kkunal1408. The issue seems to be that we are trying to create an ordering constraint that orders an instance against itself.
```console
align.schema.constraint ERROR : Failed to add constraint constraint='order' instances=List[str](__root__=['mn0_mp0', 'mn0_mp0']) direction='top_to_bottom' abut=False due to conflict with one or more of:
align.schema.constraint ERROR : constraint='horizontal_distance' abs_distance=0
align.schema.constraint ERROR : constraint='vertical_distance' abs_distance=0
align.schema.constraint ERROR : constraint='order' instances=List[str](__root__=['mn0_mp0', 'mn0_mp0']) direction='top_to_bottom' abut=False
align.cmdline ERROR : Fatal Error. …
```
> [schema] ring_oscillator constraint generation fix

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/PlacerIfc.cpp
Normalize the placer cost components;
Area by sum of constituent blocks areas;
Linear_cost and HPWL by sum of block widths and heights;
dead_area is already normalized w.r.t total area;
> normalize cost components

- align/cmdline.py
- align/main.py
- regression_summaries/render_table.py
@parijatm @854768750 @soneryaldiz @Lastdayends @arvuce22 @kkunal1408 
I want to add flow stage control (so you run any consecutive subsequence of  ['1_topology', '2_primitive', '3_pnr'])
To do this it made sense to remove support for multiple .sp files in the same input directory. This doesn't seem to be used or tested for.
I did have to create one more file, a JSON file of the primitive information generated by stage 1 and feed to stage 2.
The new command line parameters are '--flow_start' and '--flow_stop'.
I think we should eventually extend this to include a 4th stage of gds generation (I almost never want to run that).
We might even be able to defer the .gds.json generation to that stage.
> Remove multiple netlist support and add flow stage control

- .circleci/config.yml
- align/cmdline.py
- align/main.py
- align/pnr/main.py
- align/pnr/toplevel.py
- tests/pnr/test_hpwl.py
Add new command line parameter to specify the maximum number of routings to generate. This is independent of nvariants. It should improve the runtime for cases where nvariants needs to be set > 1 for quality reasons in the placer. The default is now 1.
> Separate nroutings from nvariants

- align/compiler/match_graph.py
- align/compiler/write_verilog_lef.py
- align/config/basic_template.sp
- align/config/user_template.sp
- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet/circuits.py
- tests/pdk/finfet/test_annotation.py
- tests/pdk/finfet/test_circuits.py
Please see the failing test: `tests/pdk/finfet/test_annotation.py`
The netlist below is mapped to a level shifter:
```
mp29 v4 vbias2 v2 vccx p w=2.16e-6 m=1 nf=12
mp33 vbias2 vbias2 vbias1 vccx p w=1.44e-6 m=1 nf=8
```
This is wrong as the transistor widths are not the same.
> Incorrect annotation

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
- align/gui/mockup.py
- tests/pnr/test_entrypoint2.py
@srini229 @854768750 @Lastdayends We don't seem to be finding a good solution for the matrix testcase any more. I suspect this has to do with the ILP flipping code but I'm not sure.
It is trying to minimize wire length (all the wires are short), but it doesn't seem to be using the best area solution (you would be able to flip the to middle rows around the y-axis to make the layout a square.)
To reproduce this, do the following:
```
export ALIGN_HOME=`pwd`
export ALIGN_WORK_DIR=$ALIGN_HOME/work
pytest -- tests/pnr/test_entrypoint2.py
cd $ALIGN_WORK_DIR/matrix_entrypoint2
schematic2layout.py this_doesnt_matter -s matrix -p /home/smburns/DARPA/ALIGN-public/pdks/FinFET14nm_Mock_PDK --flow_start 3_pnr --skipGDS --gui -n 40
```
It also seems that one variant is being generated even though we …
> Flipping incorrect in synthetic testcase

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- align/pnr/write_constraint.py
- tests/constraints/test_constraint.py
- tests/files/test_results/high_speed_comparator_align.pnr.const.json
- tests/files/test_results/high_speed_comparator_multiconnection.pnr.const.json
- tests/files/test_results/high_speed_comparator_portlocation.pnr.const.json
- tests/files/test_results/high_speed_comparator_symmnet.pnr.const.json
Allow user to align blocks on top, bottom, left, right and center (horizontal or vertical) as defined per  `class Align` in `align/schema/constraint.py`. Please see `tests/constraints/test_constraint.py:test_align_top_right`
Example:
```
{
"line": < { h_bottom, h_top, v_left, v_right, v_center }> ,
"const_name": "AlignBlock",
"blocks": [
"mn0",
"mn1"
]
}
```
> Generalize Align Constraint

- align/schema/checker.py
- align/schema/constraint.py
See #839 for details
Uncontrolled use of copy in the pnr frontend was causing issues with object ID based tracking variable permanence
Using hash(repr()) instead now to generate tracking variables.
> Bugfix unsat core display

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/PnRdatabase.cpp
- PlaceRouteHierFlow/PnRDB/PnRdatabase.h
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/CMakeLists.txt
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/Placer.h
- PlaceRouteHierFlow/placer/PlacerHyperparameters.h
- PlaceRouteHierFlow/placer/SeqPair.h
- align/pnr/main.py
- align/pnr/toplevel.py
- examples/cascode_current_mirror_ota/CASCODE_CURRENT_MIRROR_OTA_0.scaled_placement_verilog.json
- examples/five_transistor_ota/FIVE_TRANSISTOR_OTA_0.scaled_placement_verilog.json
- examples/high_speed_comparator/HIGH_SPEED_COMPARATOR_0.scaled_placement_verilog.json
@854768750 Here is a PR with the stub added.
Please work on the method: `void PnRdatabase::setPlacementInfoFromJson(const string& json_string)`
To test, you can try:
```
export ALIGN_HOME=/path/to/align-public
export ALIGN_WORK_DIR=$ALIGN_HOME/work
mkdir -p $ALIGN_WORK_DIR
cd $ALIGN_WORK_DIR
mkdir five_transistor_ota
cd five_transistor_ota
schematic2layout.py ../../examples/five_transistor_ota --reference_placement_verilog_json `pwd`/../../examples/five_transistor_ota/FIVE_TRANSISTOR_OTA_0.scaled_placement_verilog.json
```
Here, instead of running the placer Python procedure we are running this new C++ method with the example placement verilog json file. 
Let me know if you want this to be different. We can scale the JSON file differently if you want as well. Currently it should be in the …
> Stubs for adding new placement injection function

- PlaceRouteHierFlow/PnRDB/WriteJSON.cpp
font units get scaled by units; this is seen while importing stream in virtuoso.
> fix font scaling issue 

- align/compiler/user_const.py
- align/pnr/checker.py
- align/schema/checker.py
- align/schema/constraint.py
- align/schema/hacks.py
- align/schema/instance.py
- align/schema/subcircuit.py
- align/schema/types.py
- tests/compiler/test_user_constraint.py
- tests/compiler/test_writer.py
- tests/pnr/test_write_constraint.py
- tests/schema/test_checker.py
- tests/schema/test_constraint.py
This PR takes care of several important upgrades:
> Generic Solver Interface  + Translate entire subcircuit

- .circleci/config.yml
- PlaceRouteHierFlow/thirdparty/spdlog.cmake
This PR resolves the build failure and the build-test-coverage failure.
> Freeze spdlog to 1.9.2 and Tolerate errors in coverage tests

- align/compiler/preprocess.py
- tests/compiler/test_preprocessing.py
To reproduce: `pytest -v tests/compiler/test_preprocessing.py`
@kkunal1408 , should not the merge transistors have been removed from the database? The current implementation removes from the temporary graph but not the database.
> Merging Series and Parallel Devices

- .circleci/config.yml
- conftest.py
- tests/integration/test_integration.py
Added an environment variable to set the CI_LEVEL ('checkin', 'merge', 'all')
To run merge level CI from the command line, run:
```
CI_LEVEL=merge pytest --maxerrors 10 -vv --runnightly -- tests/integration tests/pdks
```
This is the checkin level CI command:
```
CI_LEVEL=checkin pytest --maxerrors 10 -vv --runnightly -- tests/integration tests/pdks
```
> Move block restrictions out of .circleci/config.yml

- align/primitive/main.py
- tests/pdks/test_mos.py
Primitives CM and CMFB were redundant; we have replaced these with SCM. In this branch we have modified/removed tests related to CM and CMFB
> modifying primitive names in tests/pdks/test_mos.py

- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pdk/finfet_pdk/test_transistor_array.py
The constraint was only created for PMOS but not for NMOS devices.
Also, simplified the constraint so that both NMOS and PMOS can be placed on [0,0].
> Fix PlaceOnGrid constraint generation in align/pdk/finfet

- PlaceRouteHierFlow/PnRDB/WriteJSON.cpp
- pdks/FinFET14nm_Mock_PDK/layers.json
PnR assumes "GdsDatatype" equal to 0 for drawing metal layers and Vias (PnR does not take the values for layers.json). This result in missing layer issues when we import the layouts in Virtuoso.
> modifying layers.json to recreate the issue

- align/compiler/compiler.py
- align/compiler/preprocess.py
- align/compiler/read_library.py
- align/pdk/finfet/__init__.py
- align/pdk/finfet/models.py
- align/pdk/finfet/models.sp
- align/pdk/finfet/resistor.py
- align/primitive/main.py
- align/schema/library.py
- align/schema/parser.py
- tests/compiler/test_compiler_parser.py
- tests/compiler/test_library_parsing.py
- tests/compiler/test_preprocessing.py
- tests/pdk/finfet_pdk/test_resistor.py
- tests/pnr/test_write_constraint.py
This PR allows a PDK module to define base models.
Merge parallel or stack only if the model supports this capability (model includes PARALLEL and STACK parameters).
Be consistent in handling PARALLEL and STACK parameters.
> Allow PDK to define base models

- PlaceRouteHierFlow/placer/design.cpp
- tests/pdk/finfet_pdk/test_placer.py
Addition of a constraint causes placer to hang during constraint processing
Passing test: `tests/pdk/finfet_pdk/test_placer.py::test_cmp_fast`
Hanging test: `tests/pdk/finfet_pdk/test_placer.py::test_cmp_slow`
```
DEBUG    PnR.cap_placer.Placer_Router_Cap.Placer_Router_Cap:toplevel.py:306 End CC Capacitor Placement and Router
DEBUG    PnR.placer.design.MergeNewBlockstoSymmetryGroup:toplevel.py:330 New symmetric group
```
> Placer Hangs in  PnR.placer.design.MergeNewBlockstoSymmetryGroup

- align/pdk/finfet/transistor_array.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_circuits_partial_routing.py
This PR updates partial routing in align/pdk/finfet:
```
if NEW_PARTIAL_ROUTING_FEATURE:
route single transistor primitives up to m1 excluding gate
route double transistor primitives up to m2 to improve matching
```
> Update partial routing in pdk/finfet

- .circleci/config.yml
- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/ILP_solver.h
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
- PlaceRouteHierFlow/placer/design.cpp
- align/schema/constraint.py
- tests/constraints/test_constraint.py
- tests/constraints/utils.py
Please see the failing test: `tests/constraints/test_constraint.py::test_netpriority`. 
The current placement solution is `xi0, xi1, xi2` from left to right. 
Given the following constraint: `{"constraint": "NetPriority", "nets": ["v1"], "weight": 0}`, instance `xi1` is expected to be placed on the right.
> NetPriority

- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/SeqPair.h
- PlaceRouteHierFlow/placer/unit_tests.cpp
- PlaceRouteHierFlow/unit_tests.cpp
Keeps a set of visited permutation vectors.
It now returns whether it found a solution or not.
Need to modify calls to do the right thing if a solution is not found.
> Removed infinite loop from KeepOrdering

- .circleci/config.yml
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/PlacerIfc.cpp
- align/pnr/write_constraint.py
- align/schema/constraint.py
- tests/constraints/test_constraint.py
This PR:
- Renames MatchBlocks for user to PlaceCloser (still translated to MatchBlocks for pnr)
- PlaceCloser supports multiple instances
- Add a test for functionality
Failing test: `tests/constraints/test_constraint.py::test_placecloser`
> Rename MatchBlocks to PlaceCloser

- align/compiler/create_database.py
- align/compiler/gen_abstract_name.py
- align/compiler/read_library.py
- align/compiler/util.py
- align/pdk/finfet/__init__.py
- align/pdk/finfet/digital.py
- align/pdk/finfet/gen_param.py
- align/pdk/finfet/generators.py
- align/pnr/checkers.py
- align/primitive/__init__.py
- align/primitive/default/canvas.py
- align/primitive/main.py
- tests/compiler/test_get_generator.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_circuits_partial_routing.py
- tests/pdk/finfet_pdk/test_digital.py
- tests/pdk/finfet_pdk/test_generator.py
- tests/pdk/finfet_pdk/test_identification.py
- tests/pdk/finfet_pdk/test_miscellaneous.py
- tests/pdk/finfet_pdk/test_pinless.py
- tests/pdk/finfet_pdk/test_placement_grid.py
- tests/pdk/finfet_pdk/test_placer.py
- tests/pdk/finfet_pdk/test_resistor.py
- tests/pnr/test_cap_array.py
- tests/pnr/test_check_adr.py
- tests/primitive_pdks/sample_package/__init__.py
- tests/primitive_pdks/sample_package/main.py
This PR:
- refactors get_generator method
- for packaged or installed PDK's, calls generator_class method to identify the generator
This enhancement allows using a single generator class name for a large number of models.
> Query PDK to Find Generator Class

- align/compiler/match_graph.py
- align/compiler/util.py
- align/pdk/finfet/gen_param.py
- align/primitive/main.py
- align/schema/constraint.py
- align/schema/transistor.py
- pdks/FinFET14nm_Mock_PDK/gen_param.py
- tests/compiler/test_auto_const.py
- tests/compiler/test_database.py
- tests/compiler/test_user_constraint.py
- tests/pdks/test_mos.py
To enable RADHARD MOSGenerator in p1222, we set a field in the generator dictionary in `__primitives_library__.json` (in 1_topology).
> Allow MOSGenerator styles

- align/cell_fabric/grid.py
- pdks/Bulk65nm_Mock_PDK/mos.py
- pdks/FinFET14nm_Mock_PDK/mos.py
- pdks/FinFET14nm_Mock_PDK/res.py
- tests/cell_fabric/test_grid.py
This PR revises `inverseBounds` for enclosure grids that are not monotonic.
> inverseBounds for non-monotonic grids

- align/pdk/finfet/models.sp
- tests/pdk/finfet_pdk/circuits.py
- tests/pdk/finfet_pdk/test_circuits.py
@srini229 , this PR adds one of the test circuits we discussed earlier. The test is currently failing:
`2022-05-23 20:32:46 PnR.placer.Placer.setPlacementInfoFromJson ERROR : instance_name: X_I0 concrete_template_name: NMOS_4T_38150412_X2_Y1 not found.`
> Opamp test case using poor man's cascode

- PlaceRouteHierFlow/placer/Placer.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- tests/constraints/test_constraint.py
Changes in previous PR exposed latent issue with this test case. See #1102 for discussion.
```
pytest -n 1 -vv tests/constraints/test_constraint.py::test_order_abut
```
fails with hard constraint placement violations in the _5 placement.
```
ERROR    align.schema.hacks:hacks.py:115 Solution not found due to conflict between:
ERROR    align.schema.hacks:hacks.py:117 {"constraint": "symmetric_blocks", "pairs": [["X_CCP_MP5_MP6"], ["X_CCN_MN3_MN4"], ["X_DP_MN1_MN2"], ["X_MN0"], ["X_INVN_MN12_MP14", "X_INVP_MN11_MP13"], ["X_MP7", "X_MP8"], ["X_MP9", "X_MP10"]], "direction": "V"}
ERROR    align.schema.hacks:hacks.py:117 {"constraint": "order", "instances": ["X_INVN_MN12_MP14", "X_INVP_MN11_MP13"], "direction": "left_to_right", "abut": true}
ERROR    align.schema.hacks:hacks.py:117 …
```
> Fix test_order_abut failing test case

- PlaceRouteHierFlow/placer/ILP_solver.cpp
For Symphony solver (default): runtime limit per ILP call set to (number of blocks * 1)(s).
For Cbc solver (used for place on grid constraints), runtime limit : (number of blocks * 10)(s)
> Set runtime limit for ILP solvers in SA placer

- PlaceRouteHierFlow/placer/design.cpp
- align/pdk/finfet/transistor_array.py
- examples/high_speed_comparator/high_speed_comparator.const.json
- tests/integration/test_integration.py
- tests/pdk/finfet_pdk/circuits.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdks/test_cap.py
- tests/pdks/test_constrained_generator.py
- tests/pdks/test_mos.py
- tests/pdks/test_res.py
- tests/pdks/utils.py
This PR adds a new, hierarchical test circuit. The test is currently failing due to placement being illegal. 
To reproduce:
`pytest -vv -s tests/pdk/finfet_pdk/test_circuits.py::test_analog_mux_4to1`
From the log:
`PnR.placer.Placer.PlacementCoreAspectRatio_ILP ERROR : Couldn't generate a feasible solution even after 10000 perturbations.`
There is a trivial solution to the specified constraints.
> 4-to-1 Analog Mux

- align/compiler/match_graph.py
- align/schema/translator.py
- tests/compiler/test_auto_const.py
- tests/compiler/utils.py
Please see the failing test: `test_auto_const.py::test_disable_auto_constraint_virtual`
Despite the constraint: `{"constraint": "ConfigureCompiler", "auto_constraint": False, "propagate": True}`
compiler is still generating auto-constraints for virtual hierarchy.
> Unable to turn off auto_constraint in virtual hierarchy 

- align/compiler/match_graph.py
- align/pnr/write_constraint.py
- align/schema/constraint.py
- align/schema/translator.py
- tests/compiler/test_auto_const.py
- tests/compiler/test_compiler.py
- tests/constraints/test_constraint.py
- tests/schema/test_constraint.py
This PR allows user to specify select placement constraints for a virtual hierarchy defined by `GroupBlocks`.
Example:
```python
{"constraint": "GroupBlocks",
"instances": ["mn1", "mn2", "mn3", "mn4"],
"instance_name": "xm",
"template_name": "mygroup",
"constraints": [
{"constraint": "DoNotIdentify", "instances": ["mn1", "mn2", "mn3", "mn4"]},
{"constraint": "Floorplan", "order": True, "symmetrize": True, "regions": [["mn1", "mn2", "mn3"], ["mn4"]]}
]
}
```
> Allow Constraints for GroupBlocks

- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/SeqPair.cpp
- align/pnr/build_pnr_model.py
- tests/pdk/finfet_pdk/test_placer.py
To reproduce: ` pytest -vvv -s tests/pdk/finfet_pdk/test_placer.py::test_binary_pfet`
The constraints (Floorplan and SameTemplate - auto-generated by compiler) should result in a single sequence pair for the top-level placement problem (with only three variants). Therefore, enumeration is expected. However, log file indicates that simulated annealing is used.
Netlist:
```spice
.subckt power_cell vccx vcca vg
xmp0 vcca vg vccx vccx p m=4 nf=4 nfin=4
.ends
.subckt binary vccx vcca vgfix vg[0] vg[1] vg[2] vg[3]
xi0fix vccx vcca vgfix power_cell
xi0[0] vccx vcca vg[0] power_cell
xi1[0] vccx vcca vg[1] power_cell
xi1[1] vccx vcca vg[1] power_cell
xi2[0] vccx vcca vg[2] power_cell
xi2[1] vccx vcca vg[2] power_cell
xi2[2] vccx vcca vg[2] power_cell
xi2[3] vccx vcca vg[2] power_cell
xi3[0] vccx …
```
> Sequence Pair Enumeration Does Not Kick In

- PlaceRouteHierFlow/router/A_star.cpp
- tests/pnr/test_router.py
To reproduce: `pytest -v tests/pnr/test_router.py::test_ru_resistive_route`
Please see below for the routing problem and the solution. The solution is suboptimal in resistance as it uses two additional vias (two extra V2's).
Routing problem:
Routing solution:
> Resistive Route Due to Redundant Layer Change

- align/pnr/checker.py
- align/schema/constraint.py
- examples/cascode_current_mirror_ota/cascode_current_mirror_ota.const.json
Identifying a block that is part of a placement constraint can break user intention and result in inconsistent constraints.
Example: Given
`{"constraint": "Floorplan", "symmetrize": True, "regions": [["M0", "M1", "M2"], ["M3"]}`
if annotation identifies 'M0' and 'M1', compiler changes the original constraint to:
`{"constraint": "Floorplan", "symmetrize": True, "regions": [["X_M0_M1", "M2"], ["M3"]]}`
which clearly breaks user intention.
This PR also retires Enclose, CreateAlias  constraints which are not planned to be implemented.
> DoNotIdentify Blocks in a Placement Constraint

- PlaceRouteHierFlow/PnR-pybind11.cpp
- PlaceRouteHierFlow/PnRDB/ReadConstraint.cpp
- PlaceRouteHierFlow/PnRDB/datatype.h
- PlaceRouteHierFlow/placer/ILP_solver.cpp
- PlaceRouteHierFlow/placer/design.cpp
- PlaceRouteHierFlow/placer/design.h
- Viewer/index.html
- align/pnr/main.py
- align/pnr/write_constraint.py
- align/schema/constraint.py
- tests/constraints/test_constraint.py
- tests/pdk/finfet_pdk/test_circuits.py
- tests/pdk/finfet_pdk/test_placement_grid.py
To drive development, please use the test: `tests/constraints/test_constraint.py::test_boundary_halo`
Boundary constraint definition is extended to enable horizontal and vertical halo around a subcircuit.
Example constraint:
```
{
"constraints": [
{
"max_width": 100000.0,
"max_height": 100000.0,
"halo_horizontal": 0.216,
"halo_vertical": 0.63,
"const_name": "Boundary"
}
]
}
```
For any block:
```
llx >= top_level_llx + halo_horizontal
urx <= top_level_urx - halo_horizontal
lly >= top_level_lly + halo_vertical
ury <= top_level_ury - halo_vertical
```
> Halo in Boundary Constraint

- PlaceRouteHierFlow/router/GlobalGrid.cpp
- PlaceRouteHierFlow/router/Rdatatype.h
Fix integer overflow in GR edge capacity calculation.
> use long int to calculate tile size; width * height causes int overflow
